services:
  - name: laravel-app
    type: web
    runtime: docker
    repo: https://github.com/juanbenito-aeg/er5-kaotiklash-server.git
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase: ep-bitter-rice-a9k2owbe-pooler.gwc.azure.neon.tech
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        fromDatabase: kaotiklash
      - key: DB_USERNAME
        fromDatabase: kaotiklash_owner
      - key: DB_PASSWORD
        fromDatabase: npg_U3FVTXNytOi0
